#!/usr/bin/python3
# -*-coding:UTF-8-*-
# data version: 1.1.0
# copyright (c) jason-bowen-zheng 2018-2020
# license is GPLv3

import os
# os.chdir
import readline
# None
import sys
# sys.exit, sys.version_info

ver = [1, 1, 0]

if sys.version_info[:2] < (3, 8):
    pass
else:
    print('ERROR: need python3.8')
    sys.exit(1)
