#!/usr/bin/python3
# -*- coding:UTF-8 -*-
# data version: 1.1.0
# copyright (c) jason-bowen-zheng 2018-2020
#license is GPLv3

import os
import re
import readline
import statistics as stic
import string
import sys

db = {}
ver = [1, 1, 0]
